# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "ehci_pci" "ahci" "mpt3sas" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "none";
      fsType = "tmpfs";
    };

  fileSystems."/etc" =
    { device = "zroot/nixos/etc";
      fsType = "zfs";
    };

  fileSystems."/nix" =
    { device = "zroot/nixos/nix";
      fsType = "zfs";
    };

  fileSystems."/var" =
    { device = "zroot/nixos/var";
      fsType = "zfs";
    };

  fileSystems."/var/lib" =
    { device = "zroot/nixos/var/lib";
      fsType = "zfs";
    };

  fileSystems."/var/log" =
    { device = "zroot/nixos/var/log";
      fsType = "zfs";
    };

  fileSystems."/var/spool" =
    { device = "zroot/nixos/var/spool";
      fsType = "zfs";
    };

  fileSystems."/root" =
    { device = "zroot/userdata/home/root";
      fsType = "zfs";
    };

  fileSystems."/home" =
    { device = "zroot/userdata/home";
      fsType = "zfs";
    };

  fileSystems."/home/stary" =
    { device = "zroot/userdata/home/stary";
      fsType = "zfs";
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/1BDB-8E0D";
      fsType = "vfat";
    };

  fileSystems."/data" =
    { device = "bigger/data";
      fsType = "zfs";
    };

  fileSystems."/data/syncthing" =
    { device = "bigger/data/syncthing";
      fsType = "zfs";
    };

  fileSystems."/data/syncthing/music" =
    { device = "/data/media/music";
      fsType = "none";
      options = ["bind"];
    };

  fileSystems."/export/syncthing" =
    { device = "/data/syncthing";
      fsType = "none";
      options = [ "bind" ];
    };

  fileSystems."/data/media" =
    { device = "bigger/data/media";
      fsType = "zfs";
    };

  fileSystems."/export/media" =
    { device = "/data/media";
      fsType = "none";
      options = [ "bind" ];
    };

  fileSystems."/var/lib/libvirt/images" =
    { device = "bigger/data/vm-disks";
      fsType = "zfs";
    };

  fileSystems."/data/rtorrent" =
    { device = "bigger/data/torrent";
      fsType = "zfs";
    };

  fileSystems."/data/misc" =
    { device = "bigger/data/misc";
      fsType = "zfs";
    };

  swapDevices = [ ];

  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}